version: "3"
services:
  tdlight:
    image: tdlight/tdlightbotapi:latest
    restart: unless-stopped
    user: root
    ports:
      - 8081:8081
      - 8082:8082
    networks:
      - tdlight
    environment:
      - TELEGRAM_API_ID
      - TELEGRAM_API_HASH
      - TELEGRAM_STAT
      - TELEGRAM_STAT_HIDE_SENSIBLE_DATA
      - TELEGRAM_FILTER
      - TELEGRAM_MAX_WEBHOOK_CONNECTIONS
      - TELEGRAM_VERBOSITY
      - TELEGRAM_MAX_CONNECTIONS
      - TELEGRAM_PROXY
      - TELEGRAM_LOCAL
      - TELEGRAM_NO_FILE_LIMIT
      - TELEGRAM_ALLOW_USERS
      - TELEGRAM_ALLOW_USERS_REGISTRATION
      - TELEGRAM_INSECURE
      - TELEGRAM_RELATIVE
      - TELEGRAM_MAX_BATCH
      - TELEGRAM_FILE_EXPIRATION_TIME
      - TELEGRAM_LOGS
    volumes:
      - tdlight:/var/lib/telegram-bot-api
  nginx:
    image: nginx:alpine
    user: root
    restart: always
    ports:
      - 3542:80
    networks:
      - tdlight
    volumes:
      - tdlight:/srv
      - ./nginx:/etc/nginx/conf.d/

volumes:
  tdlight:


networks:
  tdlight:
